### ISSUE TITLE
 is not allowed to be remotely executed

### ISSUE THREAD

**Issue by AOWGaming** [ole1986/a3-exile-scratchie#1]
Scripting function 'exileserver_lottery_network_re...' is not allowed to be remotely executed

**Comment by ole1986** [comment]
please provide me with your description.ext from the missionFile.
Thanks

**Comment by ole1986** [comment]
issue is not reproducible - possible configuration error.
Make sure you have added the `class ExileServer_lottery_network_request { allowedTargets=2; };` part inside the `class Functions` which is nested by the `class CfgRemoteExec`
